<a href="https://colab.research.google.com/github/jessie0628/codingwithcx/blob/master/Python_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction

Python is a modern, robust, high level programming language. It is very easy to pick up even if you are completely new to programming.

- The most recent major version of Python is Python 3, which we shall be using in this tutorial.
- Python has a simple syntax similar to the English language.
- Python uses new lines to complete a command. 
- Python relies on indentation, using whitespace, to define scope; such as the scope of loops, functions and classes.



## Python Syntax

It is important to know how to write lines of code in Python. 

### Indentation

Indentation refers to the spaces at the beginning of a code line.

Where in other programming languages the indentation in code is for readability only, the indentation in Python is very important.

Python uses indentation to indicate a block of code.


In [0]:
if 5 > 2:
    print("Five is greater than two!")

Five is greater than two!


Python will give you an error if you skip the indentation:

In [0]:
if 5 > 2:
print("Five is greater than two!")

IndentationError: expected an indented block (<ipython-input-3-a314491c53bb>, line 2)

### Comments

Python has commenting capability for the purpose of in-code documentation.

Comments start with a **#**, and Python will render the rest of the line as a comment: 

In [0]:
#This is a comment.
print("Hello, World!")

Hello, World!


## Python Variables

Variables are reserved memory locations to store values. This means that when you create a variable you reserve some space in your computer memory.

Python variables do not need explicit declaration to reserve memory space. The declaration happens automatically when you assign a value to a variable. The equal sign (=) is used to assign values to variables.

The operand to the left of the = operator is the name of the variable and the operand to the right of the = operator is the value stored in the variable.

In [0]:
x = 5
y = "John"

print(x)
print(y)

5
John


Variables can be str(Strings), int(integers), float(decimal point numbers) and many more.

We show a few common examples.


In [0]:
x = 4 # x is of type int
y = "Sally" # y is of type str
z = 4.0 # z is of type float

print(x)
print(y)
print(z)

4
Sally
4.0


Variables do not need to be declared with any particular type and can even change type after they have been set.

In [0]:
x = 4 # x is of type int
x = "Sally" # x is now of type str
print(x)

Sally


**Note**

To declare a string you can use either "..." or '...'. 

Single (') and double (") quotes are equivalent in Python.

## The Print Statement

A **function** is a set of statements that take inputs, do some specific computation and produces output. More about it is explained in the Lists section [6.4].

The print() is a built in function  which displays all of its inputs as strings, separated by spaces and follows by a linebreak:

In [0]:
print("Hello","World")

Hello World


### Printing variables

In [0]:
string1='World'
string2='!'
print('Hello' + string1 + string2) 

HelloWorld!


A easy way to print variables is by using .format() function. This is also a built in python function.



In [0]:
name = "Tobias"

print(" Hello, I am {}".format(name))

 Hello, I am Tobias


### Exercise

Try to store your name and age in variables and print the output. Fill out the missing parts to run the two cells below successufully.

In [0]:
name = 
age = 

In [0]:
print("I am {} and my age is {}".format())

## Control Flow Statements

The key thing to note about Python's control flow statements and program structure is that it uses indentation to mark blocks. Hence the amount of white space (space or tab characters) at the start of a line is very important.

### If - else

An *if* statement consists of a boolean expression followed by one or more statements, and these statements are executed if the boolean condition is true.
If the condition is not satisfied, the statements below *else* are executed.

In [0]:
x = 12
if x > 10:
    print("Hello")
else:
    print("Bye")

Hello


### Elif

To check for multiple conditions, the *elif* is used.

In [0]:
x = 10
y = 12
if x > y:
    print("x>y")
elif x < y:
    print("x<y")
else:
    print("x=y")

x<y


### For loop

The *for* loops are used when you have a block of code which you want to repeat a fixed number of times. The Python *for* statement iterates over the members of a sequence in order, executing the block each time.

When looping over integers the *range()* function is useful. It can be of two types.
- The function *range(stop)* has parameter *stop* which is the number of integers (whole numbers) to generate, starting from zero. For example, **range(3) == [0, 1, 2].**
So, in general, range(n) =  0, 1, ..., n-1


- range(m,n)= m, m+1, ..., n-1
. For example, **range(3, 6) === [3, 4, 5].**


- range(m,n,step) = m, m+step, m+step+step, ..., n-1
. For example, **range(3, 10, 2) === [3, 5, 7, 9].**


Here, += operator is used. This operator adds right operand to the left operand and assign the result to left operand.
For example, c += a is equivalent to c = c + a

In [0]:
total = 0
for i in range(5):
    print(i)
    total += i

print("total =",total)

0
1
2
3
4
total = 10


### While Loop

The *while* loop loops through a block of code as long as a specified condition is true.

while (condition) {

  // code block to be executed

}

We display the squares of first two natural numbers. 

The ****** operator in Python denotes the square. For example, c** is equivalent to c×c

In [0]:
i = 1
while i < 3:
    print(i ** 2)
    i = i+1
print('Bye')

1
4
Bye


### Exercise 

Try to print all the greetings by changing the time variable.

In [0]:
time = None

if time<12:
    print("Guten Morgen")
elif time>17:
    print("Guten Abend")
else:
    print("Guten Tag")

### Exercise
Calculate the average of first 20 numbers, that is between 0 to 20. Use any of the Loop statements.


In [0]:
average = None
# write your code here


print("Average of first 20 numbers: {}".format())

## Lists

Lists are the most commonly used data structure. Think of it as a sequence of data that is enclosed in square brackets and data are separated by a comma. Each of these data can be accessed by calling it's index value.

Lists are declared by just equating a variable to '[ ]' or list.

In [0]:
a = []

type(a)

list

### Indexing

In python, indexing starts from 0 as already seen for strings. Thus now the list x, which has two elements will have apple at 0 index and orange at 1 index.

In [0]:
x = ['apple', 'orange']

x[0]

'apple'

Indexing can also be done in reverse order. That is the last element can be accessed first. Here, indexing starts from -1. Thus index value -1 will be orange and index -2 will be apple.

In [0]:
x[-1]

'orange'

### Slicing

Slicing means accessing a sequence of data inside the list.

Slicing is done by defining the index values of the first element and the last element from the parent list that is required in the sliced list. It is written as parentlist[ a : b ] where a,b are the index values from the parent list. If a or b is not defined then the index value is considered to be the first value for a if a is not defined and the last value for b when b is not defined.

In [0]:
num = [0,1,2,3,4,5,6,7,8,9]
print(num[0:4])
print(num[4:])

[0, 1, 2, 3]
[4, 5, 6, 7, 8, 9]


### Reassigning Values

You can change values of any index of a list.


In [0]:
num[0] = 10

print(num)

[10, 1, 2, 3, 4, 5, 6, 7, 8, 9]


But you cannot assign values to a index which is more than the length of the list.

In [0]:
num[11] = 11
print(num)

IndexError: list assignment index out of range

To add more values to end of list we can use append(). We show how .append() works below.

### Built in List Functions

A **function** is a set of statements that take inputs, do some specific computation and produces output. Python provides **built-in functions** like print(), etc. but we can also create your own functions. These functions are called **user-defined functions**.

Python list has a number of functions that are built in which are always available. Some of the most used ones are:
- len()
- max() or min()
- sum()
- append()
- sort()

len(): To get the length of the list.

In [0]:
num = [0,1,2,3,4,5,6,7,8,9]

len(num)

10

max(), min(): To get maximum and minimum values in the list.

In [0]:
print(max(num))

print(min(num))

9
0


sum(): To calculate sum of all elements in the list.

In [0]:
print(sum(num))

45


Remember we tried to add 11 to num list but got an error. We can use .append() instead.

append(): Insert an element at the end of a list.

In [0]:
num.append(11)
print(num)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11]


sort(): To arrange the elements in ascending order.

In [0]:
num.sort()
print(num)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11]


### Exercise

Print the second item in the fruits list.

In [0]:
fruits = ["apple", "banana", "cherry"]

# print second item of the list
print()

Add another fruit to the fruits list. Print the updated list.


In [0]:
# add another fruit

# print the updated list
print()

## Tuple

A tuple is a collection which is ordered and unchangeable. In Python tuples are written with round brackets.

Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable.

In [0]:
mytuple = ("apple", "banana", "cherry")

print(mytuple)

('apple', 'banana', 'cherry')


You can access tuple items by referring to the index number, inside square brackets.
Indexing works the same as in lists.

In [0]:
print(mytuple[1])

banana


You can loop through a tuple:

In [0]:
for x in mytuple:
    print(x) 

apple
banana
cherry


## Dictionary

A dictionary is a collection which is unordered, changeable and indexed.

In Python dictionaries are written with curly brackets, and they have keys and values.

In [0]:
mydict ={
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(mydict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


### Accessing items

You can access the items of a dictionary by referring to its key name, inside square brackets:

In [0]:
x = mydict["model"]
print(x)

Mustang


### Change Values

You can change the value of a specific item by referring to its key name:

In [0]:
mydict["year"] = 2018

print(mydict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}


### Loop through Dictionary

You can loop through a dictionary by using a for loop.

To print all key names in the dictionary, one by one:

In [0]:
for x in mydict:
    print(x) 

brand
model
year


To print all values in the dictionary, one by one:

In [0]:
for x in mydict:
    print(mydict[x]) 

Ford
Mustang
2018


### Adding Items

Adding an item to the dictionary is done by using a new index key and assigning a value to it:

In [0]:
mydict ={
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

mydict["color"] = "red"
print(mydict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}


### Exercise 

Construct a dictionary named car with the characteristics, Brand is "Audi", Model of the car: "Q3" and Year of construction: 2001.

Then perform the following tasks:
- Get its model
- Change the year to 2019
- Add Colour of car as Blue

In [0]:
car ={
  
}

In [0]:
# get the model
model = 
print("The model of car is: {}".format(model))

In [0]:
# change the year


# print the entire dictionary
print(car)

In [0]:
# add colour


# print the entire dictionary
print(car)

## User-defined Functions

User-defined Functions can represent mathematical functions. More importantly, in programmming functions are a mechansim to allow code to be re-used so that complex programs can be built up out of simpler parts.

In [0]:
def firstfunc():
    print("Hello!")
    print("How are you?")
firstfunc() # execute the function

Hello!
How are you?


We can make our function firstfunc() to accept arguements which will store the name and then prints respective to that accepted name. To do so, add a argument within the function as shown.

In [0]:
def firstfunc(username):
    print("Hello {}." .format(username))

firstfunc("Tobias")

Hello Tobias.


### Return Statement

When the function results in some value and that value has to be stored in a variable or needs to be sent back or returned for further operation to the main algorithm, a return statement is used.

In [0]:
def times(x,y):
    z = x*y
    return z

c = times(4,5)
print(c)

20


### Exercise

Write a function to calculate Body Mass Index:

Inputs are:
- weight (kg)
- height (m)

Formula: $weight/(height)^2$

In [0]:
BMI = None
# Write your own function


print("Your BMI is: {}".format(BMI))

Your BMI is: None


## Linear Algebra

The study of linear algebra involves several types of mathematical objects like:
- **Scalars**: A scalar is just a single number
- **Vectors**: A vector is an array of numbers. The numbers are arranged in order. We can identify each individual number by its index in that ordering
- **Matrices**: A matrix is a 2-D array of numbers, so each element is identified by two indices instead of just one. 
- **Tensors**: In some cases we will need an array with more than two axes.In the general case, an array of numbers arranged on a regular grid with a variable number of axes is known as a tensor.

### Creating Scalars, Vectors and Matrices.

Scalars can be created easily like this:

In [0]:
x = 0.5
print(x)

0.5


### Numpy

A Python library is a collection of functions and methods that allows you to perform many actions without writing your own code. One such is the **Numpy** library, which is used for numerical operations.

Dealing with vectors and matrices efficiently requires the **numpy** library. Numpy supports arrays and matrices. Apart from the convenience, the numpy methods are also much faster at performing operations on matrices or arrays than performing arithmetic with numbers stored in lists.

In [0]:
import numpy as np 

In [0]:
x_vector = np.array([1.5,0,-1,2]) #i miss cx
print(x_vector)


[ 1.5  0.  -1.   2. ]


Matrices are 2-D vectors.

In [0]:
x_vector = np.arange(1038)
x_vector

array([   0,    1,    2, ..., 1035, 1036, 1037])

In [0]:
x_matrix = x_vector.reshape(6,-1)

x_matrix


array([[   0,    1,    2, ...,  170,  171,  172],
       [ 173,  174,  175, ...,  343,  344,  345],
       [ 346,  347,  348, ...,  516,  517,  518],
       [ 519,  520,  521, ...,  689,  690,  691],
       [ 692,  693,  694, ...,  862,  863,  864],
       [ 865,  866,  867, ..., 1035, 1036, 1037]])

In [0]:
print(x_matrix.shape)

(3, 3)


### Matrix Addition and Subtraction

Let's consider a small matrix of dimension 2×2, where 2×2 denotes the number of rows × the number of columns.

Let A=$\begin{bmatrix}a11 & a12\\a21 & a22\end{bmatrix}$. Consider adding a scalar value (e.g. 3) to the A.


$ A + 3 = \begin{bmatrix}a11 & a12\\a21 & a22\end{bmatrix} + 3 = \begin{bmatrix}a11+3 & a12+3\\a21+3 & a22+3\end{bmatrix}$

The same basic principle holds true for A-3:

$ A - 3 = \begin{bmatrix}a11 & a12\\a21 & a22\end{bmatrix} - 3 = \begin{bmatrix}a11-3 & a12-3\\a21-3 & a22-3\end{bmatrix}$


In [0]:
A = np.arange(4).reshape(2,2)
print(A)

[[0 1]
 [2 3]]


In [0]:
print(A+3)

[[3 4]
 [5 6]]


### Adding or Subtracting two matrices

Adding two matrices A and B:

$ A + B = \begin{bmatrix}a11 & a12\\a21 & a22\end{bmatrix} + \begin{bmatrix}b11 & b12\\b21 & b22\end{bmatrix} = \begin{bmatrix}a11+b11 & a12+b12\\a21+b21 & a22+b22\end{bmatrix}$

Subtraction would work exactly same.

In [0]:
B = np.arange(4,8).reshape(2,2)
print(B)

[[4 5]
 [6 7]]


In [0]:
A + B

array([[ 4,  6],
       [ 8, 10]])

### Matrix Multiplication

Let's assume we have matrix A of dimension 3×2 and matrix B of dimension 2×3

A=$\begin{bmatrix}a11 & a12\\a21 & a22\\a31 & a32\end{bmatrix}$, B=$\begin{bmatrix}b11 & b12 & b13\\b21 & b22 & b23\end{bmatrix}$

Then A × B = $\begin{bmatrix}a11 & a12\\a21 & a22\\a31 & a32\end{bmatrix}$ × $\begin{bmatrix}b11 & b12 & b13\\b21 & b22 & b23\end{bmatrix}$

= $\begin{bmatrix}a11b11+a12b21 & a11b12+a12b22 & a11b13+a12b23\\a21b11+a22b21 & a21b12+a22b22 & a21b13+a22b23\\a31b11+a32b21 & a31b12+a32b22 & a31b13+a32b23\end{bmatrix}$

**So, for $A_{r_{a}×c_{a}}×B_{r_{b}×c_{b}}$ , where r = row and c = column, we have two important things to remember:**

- For conformability in matrix multiplication, $c_{a}=r_{b}$, or the columns in the first operand must be equal to the rows of the second operand.
- The result will be of dimension $r_{a}×c_{b}$, or of dimensions equal to the rows of the first operand and columns equal to columns of the second operand.

In [0]:
A = np.arange(6).reshape(3,2)
B = np.arange(6,12).reshape(2,3)
print(A)
print(A.shape)
print(B.shape)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
(2, 3)


In [0]:
result = np.dot(A,B)

print(result)
print(result.shape)

[[ 9 10 11]
 [39 44 49]
 [69 78 87]]
(3, 3)


The common dimension between the matrices we multiply has to match. Otherwise, Python will throw error:

In [0]:
A = np.arange(6).reshape(6,1)
B = np.arange(6,12).reshape(2,3)

print(A.shape)
print(B.shape)

(6, 1)
(2, 3)


In [0]:
result = np.dot(A,B)

print(result)
print(result.shape)

ValueError: shapes (6,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)

Change the B matrix dimension such that the error is solved. Then the rerun the two cells above.


### Transpose of a matrix

At times it is useful to pivot a matrix for conformability- that is in order to matrix divide or multiply, we need to switch the rows and column dimensions of matrices. 

Consider the matrix A = $\begin{bmatrix}a11 & a12\\a21 & a22\\a31 & a32\end{bmatrix}$

The transpose of A, A′ = $\begin{bmatrix}a11 & a21 & a31\\a12 & a22 & a32\end{bmatrix}$

In [0]:
A = np.arange(6).reshape((3,2))
B = np.arange(8).reshape((2,4))
print("A is")
print(A)
print( "The Transpose of A is")
print (A.T)

A is
[[0 1]
 [2 3]
 [4 5]]
The Transpose of A is
[[0 2 4]
 [1 3 5]]


### Exercise

Declare two matrices, matrix A of dimension 3×2 and matrix B als of dimension 3×2.

Calculate matrix C = A × B. 

C should be of dimension 3×3.

Hint: use transpose

In [0]:
rng=np.random.default_rng()

A = 2*rng.random((3,2))
B = 3*rng.random((2,3))-4

C = np.dot(A,B)

#print(A)
#print(B)
print(C)

[[-4.36568772 -2.97860385 -4.27834636]
 [-4.10397034 -2.80582514 -3.37807397]
 [-5.69080921 -3.88677575 -5.12363119]]


## Final Exercise

Let us now try to apply all the things we learnt.

In this exercise, we will calculate the Mean Arterial Pressure (MAP) of a patient.

The input will be in form of a list. So, for a patient, patient1 = [SBP, DBP].
 
Here, SBP == Systolic Blood Pressure, DBP == Diastolic Blood Pressure.

The formula: **MAP = 1/3 * SBP + 2/3 * DBP**


Based upon the the result of MAP of each patient decide whether the patient's MAP is low, normal or high.
The normal range for MAP is 60 to 100.


In [1]:
# input the SBP and DBP of a patient
patient = [105,40]

# write a function here to calculate the mean arterial pressure.
def cal_map(patient):
  MAP = 1/3*patient[0] + 2/3*patient[1]
  return MAP

# store the map in a variable.
MAP = None

# write another function to displa whether the MAP value is low, normal or high

# Hint: use if else loop
def map_decision(MAP):
    if MAP >100: 
      print("high")
    elif MAP <60:
      print("low")
    else:
      print("normal")

MAP = cal_map(patient)
map_decision(MAP)

    



normal
